name: verificac19
description: EU Digital Green Certificate validation SDK for Flutter apps
version: 1.5.0
homepage: https://github.com/mastro993/verificac19-flutter
documentation: https://github.com/mastro993/verificac19-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.2.2
  asn1lib: ^1.1.0
  cbor: ^5.0.1
  clock: ^1.1.0
  crypto: ^3.0.1
  crypto_keys: ^0.3.0
  dart_base45: ^1.0.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  mutex: ^3.0.0
  ninja: ^3.0.8
  path: ^1.8.0
  path_provider: ^2.0.9
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.13
  x509b: ^0.2.5

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  http_mock_adapter: ^0.3.2
  injectable_generator: ^1.5.3
  isar_generator: ^2.2.1
  mockito: ^5.1.0
  retrofit_generator: ^4.0.1
