name: verificac19
description: EU Digital Green Certificate validation SDK for Flutter apps
version: 1.6.0
homepage: https://github.com/mastro993/verificac19-flutter
documentation: https://github.com/mastro993/verificac19-flutter

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.2"

dependencies:
  archive: ^3.3.6
  asn1lib: ^1.4.0
  cbor: ^5.1.2
  clock: ^1.1.1
  crypto: ^3.0.2
  crypto_keys: ^0.3.0
  dart_base45: ^1.0.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  mutex: ^3.0.1
  ninja: ^3.0.8
  path: ^1.8.2
  path_provider: ^2.0.12
  retrofit: ^3.3.1
  shared_preferences: ^2.0.17
  x509b: ^0.2.5

dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  http_mock_adapter: ^0.3.3
  injectable_generator: ^2.1.3
  isar_generator: ^3.0.5
  mockito: ^5.3.2
  retrofit_generator: ^4.2.0
